export const SUBWAY_LINES = {
  "1": { color: "#EE352E", name: "1", group: "123" },
  "2": { color: "#EE352E", name: "2", group: "123" },
  "3": { color: "#EE352E", name: "3", group: "123" },
  "4": { color: "#00933C", name: "4", group: "456" },
  "5": { color: "#00933C", name: "5", group: "456" },
  "6": { color: "#00933C", name: "6", group: "456" },
  "7": { color: "#B933AD", name: "7", group: "7" },
  A:   { color: "#0039A6", name: "A", group: "ACE" },
  C:   { color: "#0039A6", name: "C", group: "ACE" },
  E:   { color: "#0039A6", name: "E", group: "ACE" },
  B:   { color: "#FF6319", name: "B", group: "BDFM" },
  D:   { color: "#FF6319", name: "D", group: "BDFM" },
  F:   { color: "#FF6319", name: "F", group: "BDFM" },
  M:   { color: "#FF6319", name: "M", group: "BDFM" },
  G:   { color: "#6CBE45", name: "G", group: "G" },
  J:   { color: "#996633", name: "J", group: "JZ" },
  Z:   { color: "#996633", name: "Z", group: "JZ" },
  L:   { color: "#A7A9AC", name: "L", group: "L" },
  N:   { color: "#FCCC0A", name: "N", group: "NQR" },
  Q:   { color: "#FCCC0A", name: "Q", group: "NQR" },
  R:   { color: "#FCCC0A", name: "R", group: "NQR" },
  W:   { color: "#FCCC0A", name: "W", group: "NQR" },
  S:   { color: "#808183", name: "S", group: "S" },
};
